import { isMasterAdmin } from '@/lib/admin/permissions';
import { redirect } from 'next/navigation';
import { auth } from '@clerk/nextjs/server';
import { getGlobalProjectHealth } from '@/lib/ai/project-health';
import { GlobalHealthDashboard } from './GlobalHealthDashboard';

export const dynamic = 'force-dynamic';

export default async function GlobalAIPage() {
  const { userId } = await auth();
  if (!userId) redirect('/sign-in?redirect_url=/admin/ai');
  if (!(await isMasterAdmin(userId))) {
    return (
      <div className="max-w-md text-center py-12">
        <div className="text-6xl mb-4">🔒</div>
        <h1 className="text-2xl font-black mb-2">Master admin only</h1>
        <p className="text-ink-70 text-sm">This dashboard is restricted to platform owners.</p>
      </div>
    );
  }

  const health = await getGlobalProjectHealth();

  return (
    <div>
      <div className="mb-6">
        <h1 className="text-3xl font-black tracking-tight">Global AI dashboard</h1>
        <p className="text-ink-70 text-sm mt-1">
          Health scores, risk distribution, and key insights across every active project. Generated by the rule engine + DeepSeek.
        </p>
      </div>

      <GlobalHealthDashboard health={health} />
    </div>
  );
}
